import { spawn } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const NODELINK_DIR = resolve(__dirname, "../../../nodelink");
const NODELINK_ENTRY = resolve(NODELINK_DIR, "src/index.js");
const NODELINK_CONFIG = resolve(NODELINK_DIR, "config.js");
const LAVA_CONFIG = resolve(__dirname, "../../../lava.json");
const READY_SIGNAL = "Successfully listening on";
const STARTUP_TIMEOUT_MS = 30_000;

let nodelinkProcess = null;

/**
 * Writes a NodeLink config.js derived from lava.json so the embedded server
 * always uses the same host/port/password the Shoukaku client will connect to.
 */
function ensureNodelinkConfig() {
  let node = { host: "127.0.0.1", port: 2333, password: "youshallnotpass", secure: false };
  try {
    const lava = JSON.parse(readFileSync(LAVA_CONFIG, "utf-8"));
    if (lava?.nodes?.[0]) node = lava.nodes[0];
  } catch (e) {
    process.stderr.write(`[NodeLink] Warning: Failed to read lava.json, using default NodeLink configuration: ${e.message}\n`);
  }

  // Re-generate config.js every start so it stays in sync with lava.json
  const cfg = `// Auto-generated by nodelinkProcess.js — do not edit manually.
// Change lava.json to update these settings.
import defaultConfig from './config.default.js'

export default {
  ...defaultConfig,
  server: {
    host: '${node.host === 'localhost' ? '127.0.0.1' : node.host}',
    port: ${node.port},
    password: '${node.password}',
    useBunServer: false
  },
  cluster: {
    ...defaultConfig.cluster,
    enabled: false,
    workers: 1
  },
  logging: {
    ...defaultConfig.logging,
    level: 'warn',
    debug: {
      all: false, request: false, session: false, player: false,
      filters: false, sources: false, lyrics: false, youtube: false,
      'youtube-cipher': false, sabr: false, potoken: false
    }
  }
}
`;
  writeFileSync(NODELINK_CONFIG, cfg, "utf-8");
}

/**
 * Starts the embedded NodeLink audio server and waits until it is ready.
 * @param {import("../bot/structures/client.js").ExtendedClient} client
 * @returns {Promise<void>}
 */
export async function startNodelink(client) {
  if (!existsSync(NODELINK_ENTRY)) {
    client.log(
      "NodeLink submodule not found. Run: git submodule update --init --recursive",
      "error",
    );
    return;
  }

  ensureNodelinkConfig();

  return new Promise((resolve, reject) => {
    client.log("Starting embedded NodeLink audio server...", "info");

    nodelinkProcess = spawn(
      process.execPath,
      ["--dns-result-order=ipv4first", NODELINK_ENTRY],
      {
        cwd: NODELINK_DIR,
        stdio: ["ignore", "pipe", "pipe"],
        env: { ...process.env },
      },
    );

    const timeout = setTimeout(() => {
      reject(new Error("NodeLink failed to start within the timeout period."));
    }, STARTUP_TIMEOUT_MS);

    const onData = (data) => {
      const text = data.toString();
      if (text.includes(READY_SIGNAL)) {
        clearTimeout(timeout);
        nodelinkProcess.stdout.off("data", onData);
        client.log("NodeLink audio server is ready.", "success");
        resolve();
      }
      // Forward NodeLink warnings/errors only
      if (text.includes("[WARN]") || text.includes("[ERROR]")) {
        process.stderr.write(`[NodeLink] ${text}`);
      }
    };

    nodelinkProcess.stdout.on("data", onData);
    nodelinkProcess.stderr.on("data", (data) => {
      process.stderr.write(`[NodeLink] ${data}`);
    });

    nodelinkProcess.on("error", (err) => {
      clearTimeout(timeout);
      reject(new Error(`NodeLink process error: ${err.message}`));
    });

    nodelinkProcess.on("exit", (code, signal) => {
      if (code !== 0 && code !== null) {
        client.log(
          `NodeLink exited unexpectedly (code ${code}, signal ${signal}). Music will be unavailable.`,
          "error",
        );
      }
    });

    // Graceful shutdown: stop NodeLink when the bot process exits
    process.once("exit", stopNodelink);
    process.once("SIGINT", () => { stopNodelink(); process.exit(0); });
    process.once("SIGTERM", () => { stopNodelink(); process.exit(0); });
  });
}

/**
 * Stops the embedded NodeLink audio server.
 */
export function stopNodelink() {
  if (nodelinkProcess && !nodelinkProcess.killed) {
    nodelinkProcess.kill("SIGTERM");
    nodelinkProcess = null;
  }
}
/**@codeStyle - https://google.github.io/styleguide/tsguide.html */

